apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-operator-system
resources:
- ../../tls

secretGenerator:
  - name: ironic-credentials
    files:
    - username=ironic-username
    - password=ironic-password
  - name: ironic-inspector-credentials
    files:
    - username=ironic-inspector-username
    - password=ironic-inspector-password

patches:
- path: credentials_patch.yaml
