apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/metal3-io/baremetal-operator/config/namespace?ref=release-0.3
- https://github.com/metal3-io/baremetal-operator/config/default?ref=release-0.3
patches:
- patch: |
    # Enable test mode (fixture provider instead of ironic)
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --test-mode
    # Don't try to pull again the pre-loaded image
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
  target:
    kind: Deployment
    name: controller-manager
images:
- name: quay.io/metal3-io/baremetal-operator
  newTag: release-0.3
