apiVersion: v2
name: baremetal-operator
description: The Bare Metal Operator implements a Kubernetes API for managing bare metal hosts. It maintains an inventory of available hosts as instances of the BareMetalHost Custom Resource Definition.
type: application
version: 0.1.0
appVersion: "0.12.1"
dependencies:
- name: cert-manager
  repository: https://charts.jetstack.io
  version: "1.19.2"
  condition: cert-manager.enabled
