---
apiVersion: v1
kind: Secret
metadata:
  name: worker-0-bmc-secret
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=

---
apiVersion: metalkube.org/v1alpha1
kind: BareMetalHost
metadata:
  name: worker-0
spec:
  online: true
  bmc:
    address: libvirt://192.168.122.1:6233/
    credentialsName: worker-0-bmc-secret
  bootMACAddress: "00:1a:74:74:e5:cb"
  image:
    url: "http://172.22.0.1/images/redhat-coreos-maipo-latest.qcow2"
    checksum: "97830b21ed272a3d854615beb54cf004"
  userData:
    name: worker-user-data
    namespace: openshift-machine-api
