apiVersion: apps/v1
kind: Deployment
metadata:
  name: metalkube-baremetal-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metalkube-baremetal-operator
  template:
    metadata:
      labels:
        name: metalkube-baremetal-operator
    spec:
      serviceAccountName: metalkube-baremetal-operator
      containers:
        - name: baremetal-operator
          image: quay.io/metalkube/baremetal-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - /baremetal-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "baremetal-operator"
        # Temporary workaround to talk to an external Ironic process until Ironic is running in this pod.
        - name: ironic-proxy
          image: alpine/socat
          command: ["socat", "tcp-listen:6385,fork,reuseaddr", "tcp-connect:172.22.0.1:6385"]
          imagePullPolicy: Always
