apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "baremetal-operator.fullname" . }}
  labels:
    {{- include "baremetal-operator.labels" . | nindent 4 }}
data:
  IRONIC_ENDPOINT: {{ .Values.ironic.external.url }}
