{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "baremetal-operator.fullname" . }}-webhook
  labels:
    {{- include "baremetal-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
  - port: {{ .Values.webhook.service.port }}
    targetPort: webhook
    protocol: TCP
    name: webhook
  selector:
    {{- include "baremetal-operator.selectorLabels" . | nindent 4 }}
{{- end }}
