{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "baremetal-operator.fullname" . }}-metrics
  labels:
    {{- include "baremetal-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "baremetal-operator.selectorLabels" . | nindent 4 }}
{{- end }}
