{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace}}/{{ .Values.webhook.certificate.existingCertificate.name | default (printf "%s" (include "baremetal-operator.fullname" .)) }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta
  clientConfig:
    service:
      name: {{ include "baremetal-operator.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-metal3-io-v1alpha1-baremetalhost
  failurePolicy: Fail
  name: baremetalhost.metal3.io
  rules:
  - apiGroups:
    - metal3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - baremetalhosts
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta
  clientConfig:
    service:
      name: {{ include "baremetal-operator.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-metal3-io-v1alpha1-bmceventsubscription
  failurePolicy: Fail
  name: bmceventsubscription.metal3.io
  rules:
  - apiGroups:
    - metal3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bmceventsubscriptions
  sideEffects: None
{{- end }}
