apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This overlay extends the e2e overlay with non-default Ironic ports
# for use in upgrade tests. This allows upgrade tests to run on
# a separate kind cluster without conflicting with the main e2e cluster.

resources:
- ../e2e

configMapGenerator:
- name: ironic
  namespace: baremetal-operator-system
  behavior: replace
  envs:
  - ironic.env
