apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: baremetal-operator-system
# namePrefix: baremetal-operator-
resources:
- ../../base

components:
- ../../components/basic-auth
- ../../components/tls

# Example of how to generate config map
# configMapGenerator:
# - envs:
#   - ironic_bmo.env
#   name: ironic-bmo-configmap
#   behavior: create

# When using TLS, the ironic-httpd container is acting as a reverse-proxy.
# This means that we need to add the basic-auth related environment
# variables on ironic-httpd with this patch.
patches:
- path: basic-auth_tls.yaml
# Example for how to generate the necessary secrets:
# secretGenerator:
# - behavior: create
#   files:
#   - htpasswd=ironic-htpasswd
#   name: ironic-htpasswd
#   type: Opaque
