apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-operator-system
resources:
- ../

secretGenerator:
  - name: ironic-cacert
    files:
    - crt=ca.crt

patchesStrategicMerge:
- tls_ca.yaml
