apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../namespace

components:
  - ../../components/basic-auth
  - ../../components/tls
# Example for how to generate the necessary secrets:
# secretGenerator:
#   - name: ironic-credentials
#     files:
#     - username=ironic-username
#     - password=ironic-password
#   - name: ironic-inspector-credentials
#     files:
#     - username=ironic-inspector-username
#     - password=ironic-inspector-password
