apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-operator-system
resources:
- ../../../tls/keepalived

configMapGenerator:
- behavior: create
  envs:
  - ironic-htpasswd
  name: ironic-htpasswd
- behavior: create
  envs:
  - ironic-inspector-htpasswd
  name: ironic-inspector-htpasswd

secretGenerator:
- name: ironic-auth-config
  files:
  - auth-config=ironic-auth-config
- name: ironic-inspector-auth-config
  files:
  - auth-config=ironic-inspector-auth-config

patchesStrategicMerge:
- auth.yaml
