# permissions for end users to edit hostclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hostclaim-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: baremetal-operator
    app.kubernetes.io/part-of: baremetal-operator
    app.kubernetes.io/managed-by: kustomize
  name: hostclaim-editor-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - hostclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - hostclaims/status
  verbs:
  - get
