
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.0
  creationTimestamp: null
  name: firmwareschemas.metal3.io
spec:
  group: metal3.io
  names:
    kind: FirmwareSchema
    listKind: FirmwareSchemaList
    plural: firmwareschemas
    singular: firmwareschema
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: FirmwareSchema is the Schema for the firmwareschemas API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FirmwareSchemaSpec defines the desired state of FirmwareSchema
            properties:
              hardwareModel:
                description: The hardware model associated with this schema
                type: string
              hardwareVendor:
                description: The hardware vendor associated with this schema
                type: string
              schema:
                additionalProperties:
                  description: Additional data describing the firmware setting
                  properties:
                    allowable_values:
                      description: The allowable value for an Enumeration type setting.
                      items:
                        type: string
                      type: array
                    attribute_type:
                      description: The type of setting.
                      enum:
                      - Enumeration
                      - String
                      - Integer
                      - Boolean
                      - Password
                      type: string
                    lower_bound:
                      description: The lowest value for an Integer type setting.
                      type: integer
                    max_length:
                      description: Maximum length for a String type setting.
                      type: integer
                    min_length:
                      description: Minimum length for a String type setting.
                      type: integer
                    read_only:
                      description: Whether or not this setting is read only.
                      type: boolean
                    reset_required:
                      description: Whether or not a reset is required after changing
                        this setting.
                      type: boolean
                    unique:
                      description: Whether or not this setting's value is unique to
                        this node, e.g. a serial number.
                      type: boolean
                    upper_bound:
                      description: The highest value for an Integer type setting.
                      type: integer
                  type: object
                description: Map of firmware name to schema
                type: object
            required:
            - schema
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
