name: Periodic E2E Test Optional release-0.9

on:
  schedule:
  # Run every day at 05:20 UTC (it is recommended to avoid running at the start of the hour)
  - cron: '20 5 * * *'

permissions: {}

jobs:
  periodic-e2e-test-optional:
    if: github.repository == 'metal3-io/baremetal-operator'
    strategy:
      fail-fast: false
      matrix:
        bmc-protocol:
        - redfish
        - redfish-virtualmedia
        - ipmi
    uses: ./.github/workflows/e2e-test.yml
    with:
      bmc-protocol: ${{ matrix.bmc-protocol }}
      ginkgo-focus: upgrade
      ref: release-0.9
    permissions:
      contents: read
