# adapted from github.com/kubernetes-sigs/cluster-api/.github/workflows/pr-gh-workflow-approve.yaml
# this workflow approves workflows if the PR has /ok-to-test
# related Prow feature request https://github.com/kubernetes/test-infra/issues/25210

name: Approve GH Workflows

on:
  pull_request_target:
    types: [edited, labeled, reopened, synchronize]

permissions: {}

jobs:
  approve:
    name: Approve on ok-to-test
    runs-on: ubuntu-latest

    permissions:
      actions: write

    if: contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    steps:
    - name: Wait for workflows to be created
      run: sleep 10
    - name: Update PR
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      continue-on-error: true
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const result = await github.rest.actions.listWorkflowRunsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event: "pull_request",
            status: "action_required",
            head_sha: context.payload.pull_request.head.sha,
            per_page: 100
          });

          for (var run of result.data.workflow_runs) {
            await github.rest.actions.approveWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: run.id
            });
          }
